services:
    build:
        class:     'Opine\Build'
        arguments: ['%root%', '@fieldModel', '@pubSubModel', '@collectionModel', '@helperModel', '@configModel', '@formModel', '@bundleModel', '@cache', '@search', '@route', '@containerCache', '@handlebarService', '@languageModel']