parameters:

services:
    slim:
        class:     'Slim\Slim'
        calls:
            - [registerAutoloader, []]
    build:
        class:     'Build\Build'
        arguments: ['@pubSubBuild', '@collectionRoute', '@helperRoute', '@configRoute', '@filter', '@cache']
    pubSubBuild:
        class:     'PubSub\PubSubBuild'
    topic:
        class:     'PubSub\Topic'
        arguments: ['@container']
        calls:
            - [load, ['%root%']]
    separation:
        class:     'Separation\Separation'
        arguments: ['%root%', '@handlebars', '@cache']
    collectionRoute:
        class:     'Collection\CollectionRoute'
        arguments: ['@slim', '@db', '@separation', '@topic']
    formRoute:
        class:     'Form\FormRoute'
        arguments: ['@slim', '@formModel', '@separation', '@topic']
    formModel:     
        class:     'Form\FormModel'
        arguments: ['@db', '@topic']
    helperRoute:
        class:     'Helper\HelperRoute'
        arguments: ['@slim', '@handlebars']
    configRoute:
        class:     'Config\ConfigRoute'
        arguments: ['@config', '@cache']
    filter:
        class:     'Filter\Filter'
    cache:
        class:     'Cache\Cache'
    imageResizer:
        class:     'ImageResizer\ImageResizer'
        arguments: ['@slim']
    cache:
        class:     'Cache\Cache'
    handlebars:
        class:     'Handlebars\Handlebars'
    config:
        class:     'Config\Config'
        arguments: ['@cache']
    db:
        class:     'DB\Mongo'
        arguments: ['@config']
    request:
        class:     'Form\RequestCurrent'
    document:
        class:     'DB\DocumentCurrent'
