parameters:

services:
    slim:
        class:     'Slim\Slim'
        calls:
            - [registerAutoloader, []]
    build:
        class:     'Build\Build'
        arguments: ['@pubSubBuild', '@collectionRoute', '@helperRoute', '@configRoute', '@filter', '@cache']
    pubSubBuild:
        class:     'PubSub\PubSubBuild'
    topic:
        class:     'PubSub\Topic'
        arguments: ['@container']
        calls:
            - [load, ['%root%']]
    separation:
        class:     'Separation\Separation'
        arguments: ['%root%', '@handlebars', '@cache', '@config']
    collectionRoute:
        class:     'Collection\CollectionRoute'
        arguments: ['@slim', '@db', '@separation', '@response']
    field:
        class:     'Field\Field'
        arguments: ['@db', '@captcha']
    captcha:
        class:     'Captcha\Captcha'
    formRoute:
        class:     'Form\FormRoute'
        arguments: ['@slim', '@form', '@post', '@separation', '@topic', '@response']
    form:
        class:     'Form\Form'
        arguments: ['%root%', '@field', '@post', '@db', '@response']
    managerRoute:
        class:     'Manager\ManagerRoute'
        arguments: ['@authentication', '@separation', '@slim', '@form', '@manager']
    manager:
        class:     'Manager\Manager'
        arguments: []
    authentication:
        class:     'Authentication\Authentication'
        arguments: ['@db', '@config','@separation', '@response']
    helperRoute:
        class:     'Helper\HelperRoute'
        arguments: ['@slim', '@handlebars']
    configRoute:
        class:     'Config\ConfigRoute'
        arguments: ['@config', '@cache']
    filter:
        class:     'Filter\Filter'
        arguments: ['@response']
    cache:
        class:     'Cache\Cache'
    imageResizer:
        class:     'ImageResizer\ImageResizer'
        arguments: ['@slim']
    cache:
        class:     'Cache\Cache'
    handlebars:
        class:     'Handlebars\Handlebars'
    config:
        class:     'Config\Config'
        arguments: ['%root%', '@cache']
    db:
        class:     'DB\Mongo'
        arguments: ['@config']
    post:
        class:     'HTTP\Post'
    response:
        class:     'HTTP\Response'
    person:
        class:     'Person\Person'
        arguments: ['@db']
    errors:
        class:     'Errors\Errors'
        arguments: ['@config', '@topic', '@separation']
    mail:
        class:     'Mail\Mail'
        arguments: ['@mailSES', '@config', '@errors']
    mailSES:
        class:     'Mail\SES'
        arguments: ['@config']