services:
    build:
        class:     Opine\Build\Service
        arguments:
            - %root%
            - "@cache"
            - "@buildConfig"
            - "@buildBundles"
            - "@buildContainer"
            - "@buildRoute"
            - "@buildTopics"
    buildBundles:
        class: Opine\Build\Bundles
        arguments:
            - "@bundleBuild"
    buildConfig:
        class: Opine\Build\Config
        arguments:
            - "@configModel"
    buildContainer:
        class: Opine\Build\Container
        arguments:
            - %root%
            - "@containerCache"
    buildRoute:
        class: Opine\Build\Route
        arguments:
            - %root%
            - "@route"
            - "@routeModel"
    buildTopics:
        class: Opine\Build\Topics
        arguments:
            - "@pubSubModel"
